version: '3.8'

services:
  parking-read:
    container_name: parking-read-service
    image: 090188239653.dkr.ecr.ap-northeast-2.amazonaws.com/parking-read-service
    volumes:
      - /home/ubuntu/config/parking-read/application.yml:/config/parking-read/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/parking-read/application.yml
    ports:
      - "9000:9000"
    env_file:
      - /home/ubuntu/env/.env.parking-read
    networks:
      - backend

networks:
  backend:
    external: true