name: Deploy Notification from Docker ECR to EC2

on:
  push:
    branches:
      - dev
      - chore/cicd-init-setup
      - fix/cicd-path

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test --no-daemon

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t notification-service:latest .

      - name: Tag Docker Image
        run: docker tag notification-service:latest ${{ steps.login-ecr.outputs.registry }}/notification-service:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/notification-service:latest

      - name: Copy docker-compose-notification.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose-notification.yml"
          target: "~/"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 환경변수 파일 생성
            mkdir -p ~/env
            
            cat > ~/env/.env.notification << EOF
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EUREKA_HOST=${{ secrets.EUREKA_HOST }}
            KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            FIREBASE_SERVICE_ACCOUNT_JSON_BASE64=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}
            EOF
            
            # application.yml 파일을 컨테이너가 접근 가능한 위치에 생성
            mkdir -p ~/config/notification
            cat > ~/config/notification/application.yml << 'EOL'
            ${{ secrets.APPLICATION_YML }}
            EOL
            
            docker pull ${{ steps.login-ecr.outputs.registry }}/notification-service:latest
            docker compose -f docker-compose-notification.yml down
            docker compose -f docker-compose-notification.yml up -d
            docker image prune -f
